### ISSUE TITLE
ASCII Error when using Title criterium with Umlauts in collections

### ISSUE THREAD

**Issue by jmevissen** [plone/plone.formwidget.querystring#11]
using the Title criterium with german umlauts in a collection raises an ASCII error, when reediting 
the collection.
The error ouccurs in the rendering of the input field in:
plone.formwidget.querystring.input.pt (Line 34)

following change fixes the problem:
from (Line 34):
tal:attributes="name python:str(fieldName)+'.v:records'; value python:row['v']"
to (Line 34):
tal:attributes="name python:str(fieldName)+'.v:records'; value python:row['v'].decode('utf-8')"

**Comment by mauritsvanrees** [comment]
Looks like this was fixed a while ago with https://github.com/plone/plone.formwidget.querystring/commit/0ccfe10b713925015739ebc2f584de61feb1bf5a
This is included since release 1.1.4 (current latest release is 1.1.5, probably soon 1.1.6).
